service: lambda-ssr
frameworkVersion: '2 || 3'
app: lambda-ssr

custom:
  serverless-offline:
    httpPort: 3005
    includeModules: true # add excluded modules to the bundle
    noPrependStageInUrl: true #remove stage /dev from url
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules:
    packager: 'yarn' # Packager that will be used to package your external modules
    excludeFiles: /**/*.test.js # Provide a glob for files to ignore

provider:
  name: aws
  lambdaHashingVersion: '20201221'
  runtime: nodejs14.x

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  static:
    name: lambda-static
    handler: ssr.staticHandler
    events:
      - http:
          method: GET
          path: /static/{proxy+}
          cors: true
      - http:
          method: GET
          path: /favicon.ico
          cors: true
      - http:
          method: GET
          path: /manifest.json
          cors: true
      - http:
          method: GET
          path: /logo192.png
          cors: true

  ssr:
    name: lambda-ssr
    handler: ssr.apiHandler
    events:
      - http:
          method: GET
          path: /
          cors: true
      - http:
          method: ANY
          path: /{proxy+}
          cors: true

